server:
  port: 8020


kafka:
  bootstrap-servers: 192.168.99.100:9092
  topic:
    personEvent: dst.hs.kafkapoc.personevent

  
spring:
  application:    name: person-event-processor
    
  datasource:
    name: AAMEMBERS
    initialization-mode: embedded
    platform: h2
    url: jdbc:h2:mem:AAMEMBERS
    username: sa
    password: 
    driver-class-name: org.h2.Driver   
        
  jpa:    show-sql: true
    hibernate:      ddl-auto: validate #create

  h2:    console:      enabled: true
      path: "/h2" 
      

logging:
  level:
    org.springframework.data.rest.webmvc: WARN
             
